#!/data/data/com.termux/files/usr/bin/bash
# ONE-TIME phone setup: makes phone_start.sh run automatically when Android boots.
#
# Prereqs (must install Termux:Boot app once from F-Droid):
#   https://f-droid.org/en/packages/com.termux.boot/
#   Then open Termux:Boot once so Android registers it.
#
# After that, run this script ONCE on the phone:
#   ./scripts/install_phone_autostart.sh
#
# It creates ~/.termux/boot/start-kalike which Android runs at every boot.

set -e

cd "$(dirname "$0")/.."
APP_DIR="$(pwd)"
BOOT_DIR="$HOME/.termux/boot"
BOOT_FILE="$BOOT_DIR/start-kalike"

mkdir -p "$BOOT_DIR"

cat > "$BOOT_FILE" <<EOF
#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by install_phone_autostart.sh — runs at phone boot.
termux-wake-lock
cd "$APP_DIR"
./scripts/phone_start.sh >> boot.log 2>&1
EOF

chmod +x "$BOOT_FILE"

echo "Autostart installed at: $BOOT_FILE"
echo
echo "Verifying Termux:Boot app is installed..."
if [ -d "/data/data/com.termux.boot" ]; then
    echo "  OK — Termux:Boot app is present."
else
    echo "  WARNING — Termux:Boot app not detected."
    echo "  Install it from F-Droid: https://f-droid.org/en/packages/com.termux.boot/"
    echo "  After installing, open it once, then reboot to test."
fi
echo
echo "Also: open Android Settings -> Apps -> Termux -> Battery -> Unrestricted"
echo "(Same for Termux:Boot.) Without this, Android can suspend the watchdog."
echo
echo "To test without rebooting, run: ./scripts/phone_start.sh"
echo "After next reboot, the app should come up on its own."
